---
- hosts: ubuntu
  become: true 

  tasks:

  - name: Allow OpenSSH
    community.general.ufw:
      rule: allow
      name: OpenSSH
    
  - name: Set default policy - deny entry
    community.general.ufw:
      direction: incoming
      policy: deny

  - name: Set default policy - allow exit
    community.general.ufw:
      direction: outgoing
      policy: allow

  - name: Enable ufw and reboot
    community.general.ufw:
      state: enabled
      logging: on
